# Generated by Django 3.2 on 2024-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=300)),
                ('genericName', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('expieryDate', models.DateField()),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('shelfNo', models.CharField(blank=True, max_length=300, null=True)),
                ('unit', models.CharField(max_length=300)),
                ('group', models.CharField(blank=True, max_length=300, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('supplierPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('salePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('howToUse', models.TextField()),
                ('sideEffects', models.TextField()),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
