# Generated by Django 3.2 on 2024-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generalmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('secondName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('idNumber', models.IntegerField()),
                ('employeeId', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=600)),
            ],
        ),
    ]
