# Generated by Django 3.2 on 2024-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
