# Generated by Django 3.2 on 2024-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_permissions_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='generalMedicine',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
