# Generated by Django 3.2 on 2024-04-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240401_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expiery', models.DateTimeField()),
                ('price', models.IntegerField(null=True)),
                ('supplierPrice', models.IntegerField(null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('shelf', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=200)),
                ('genericName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('usage', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField()),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('salerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='medicineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine'),
        ),
    ]
