# Generated by Django 3.2 on 2024-04-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240401_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='supplierId',
        ),
        migrations.CreateModel(
            name='supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('supplierId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
    ]
