# Generated by Django 3.2 on 2024-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240401_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='supplierPrice',
        ),
        migrations.AddField(
            model_name='supplies',
            name='supplierPrice',
            field=models.IntegerField(null=True),
        ),
    ]
