# Generated by Django 3.2 on 2024-04-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20240401_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='medicineId',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='batchId',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='salerId',
            new_name='saler',
        ),
        migrations.RenameField(
            model_name='supplies',
            old_name='batchId',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='supplies',
            old_name='supplierId',
            new_name='supplier',
        ),
    ]
