# Generated by Django 3.2 on 2024-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_users_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='saler',
        ),
        migrations.AddField(
            model_name='sales',
            name='saler_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='deleteTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
