# Generated by Django 3.2 on 2024-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20240417_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
