# Generated by Django 3.2 on 2024-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20240419_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
