# Generated by Django 3.2 on 2024-04-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_sales_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='saler_id',
            new_name='seler_id',
        ),
    ]
