# Generated by Django 3.2 on 2024-04-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_saler_id_sales_seler_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='seler_id',
            new_name='seller_id',
        ),
    ]
